# Generated by Django 4.2 on 2024-02-02 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("warehouse_type", models.CharField(max_length=50)),
                ("github_repo_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ("full_name",),
            },
        ),
        migrations.CreateModel(
            name="Pipelineconfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("Manual", "Manual"),
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                        ],
                        default="Manual",
                        max_length=7,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipelineconfig",
                        to="dalgo_admin_app.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Datasource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                ("number_of_streams", models.PositiveIntegerField()),
                ("last_sync_date", models.DateTimeField()),
                ("last_sync_status", models.TextField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasource",
                        to="dalgo_admin_app.client",
                    ),
                ),
            ],
        ),
    ]
